name: totalist_flutter
description: "Totalist — vienkāršs uzdevumu un kalendāra rīks (Flutter)."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Lokalizācija no Flutter SDK (obligāti, lai strādātu lv tulkojumi)
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI un kalendārs
  google_fonts: ^6.3.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

